config/routes.rb
Rails.application.routes.draw do

  resources :sayers
  resources :heys

 root 'heys#index'

end

app/models/hey.rb
class Hey < ActiveRecord::Base
  belongs_to :sayer
end

app/models/sayer.rb
class Sayer < ActiveRecord::Base
  has_many :heys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/heys_controller.rb
class HeysController < ApplicationController
  def index
    # params.inspect
    page = (params[:page]).to_i
    heys  = Hey.limit(25).offset(page * 10)
    render locals: { heys: heys, page: page }
  end


  def show
    hey = Hey.find(params[:id])
    render locals: { hey: hey }
  end

  def new
    hey = Hey.new
    render locals: { hey: hey }
  end

  def create
    hey = Hey.new
    hey.body = params.fetch(:hey).fetch(:body)
    hey.sayer_id = params.fetch(:hey).fetch(:sayer_id)
    hey.save
      if hey.save
        redirect_to heys_path
      else
        redirect_to :new
      end
  end

  def update
  end

  def destroy
  end

end

app/controllers/sayers_controller.rb
class SayersController < ApplicationController
  def index
    render locals: { sayers: Sayer.all }
  end

  def show
    render locals: { sayer: Sayer.find(params[:id]) }
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heys_helper.rb
module HeysHelper
end

app/helpers/sayers_helper.rb
module SayersHelper
end

app/views/heys/create.html.erb
<h1>Heys#create</h1>
<p>Find me in app/views/heys/create.html.erb</p>

app/views/heys/destroy.html.erb
<h1>Heys#destroy</h1>
<p>Find me in app/views/heys/destroy.html.erb</p>

app/views/heys/index.html.erb
<!-- <p>Find me in app/views/heys/index.html.erb</p> -->

<h3>Your friends have been saying Hey!<h3>
<p>
  <ul>
    <% heys.each do |hey| %>
    <li>
      <section class="heys_list">
      <a href="/heys/<%= hey.id %>"><%= hey.body %></a>
       ---by <%= hey.sayer.handle %>

      </section>
    </li>
      <% end %>
  </ul>
</p>
<%= link_to( "Next Page", root_path(page: page + 1)) %>

app/views/heys/new.html.erb
<h3>Say Hey to all your friends!<h3>
<h4>Heys are quick comments 50 characters or less. Enter your Hey and click submit</h4>

<section>
<%= form_for(hey) do |f| %>
  <p>
  <%= f.label :body %>
  <%= f.text_field :body %>
  </p>

  <p>
  <%= f.label :sayer_id %>
  <%= f.text_field :sayer_id %>
  </p>

  <%= f.submit %>
<% end %>
</section>

app/views/heys/show.html.erb
<h1>SayHey!</h1>
<!-- <p>Find me in app/views/heys/show.html.erb</p>
 -->
<h3>Your friends have been saying Hey!<h3>

<section class="single_hey">
  <h4>
    <%= hey.sayer.handle %> says:
  </h4>
    <p><%= hey.body %></p>
    <br>
    <p>Go <%= link_to( "Home", root_path(:page)) %>
      to view another Hey.
    </p>


</section>

app/views/heys/update.html.erb
<h1>Heys#update</h1>
<p>Find me in app/views/heys/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sayheyapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<header><%= link_to( "SayHey!", new_hey_path)%></header>
<body>

<%= yield %>

</body>


<footer>
  <%= link_to( "Back to top", root_path(:page)) %>
</footer>
</html>

app/views/sayers/create.html.erb
<h1>Sayers#create</h1>
<p>Find me in app/views/sayers/create.html.erb</p>

app/views/sayers/destroy.html.erb
<h1>Sayers#destroy</h1>
<p>Find me in app/views/sayers/destroy.html.erb</p>

app/views/sayers/index.html.erb
<h1>SayHey!</h1>
<h6>Find me in app/views/sayers/index.html.erb<h6>

app/views/sayers/show.html.erb
<h1>Sayers#show</h1>
<p>Find me in app/views/sayers/show.html.erb</p>

app/views/sayers/update.html.erb
<h1>Sayers#update</h1>
<p>Find me in app/views/sayers/update.html.erb</p>